<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Amallar',
    'Active' => 'Aktiv',
    'Add Book' => 'Kitob qo\'shish',
    'All' => 'Hammasi',
    'Are you sure to delete this item?' => 'Rostdan ham o\'chirishga rozimisiz?',
    'Book Listing' => 'Kitoblar ro\'yxati',
    'CSV' => 'CSV',
    'Clear selection' => 'Tanlanganlarni bekor qilish',
    'Collapse' => 'Yig\'ish',
    'Collapse All' => 'Hammasini yig\'ish',
    'Comma Separated Values' => 'Vergul orqali ajratilgan qiymatlar',
    'Delete' => 'O\'chirish',
    'Disable any popup blockers in your browser to ensure proper download.' => 'To\'g\'ri yuklab olish uchin brauzeringizdagi popap bloklovchilarni o\'chirib qo\'ying.',
    'Download Selected' => 'Tanlanganlarni yuklab olish',
    'Excel' => '',
    'Expand' => 'Yoyish',
    'Expand All' => 'Hammasini yoyish',
    'Export' => 'Eksport',
    'Export All Data' => 'Hammasini eksport qilish',
    'Export Page Data' => 'Sahifadagilarni eksport qilish',
    'ExportWorksheet' => 'Jadvaldagilarni eksport qilish',
    'Failed to update editable data due to an unknown server error' => 'Noma\'lum server xatoligi tufayli qiymatlar yangilanmadi',
    'Generated' => 'Hosil qilindi',
    'Generating the export file. Please wait...' => 'Eksport fayl hosil qilinyapti. Iltimos kuting...',
    'Grid Export' => 'Jadvalni eksport qilish',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Noaktiv',
    'Invalid editable index or model form name' => 'Xato indeks yoki forma model nomi',
    'Invalid or bad editable data' => 'Xato qiymat',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => '',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Hech narsa topilmadi',
    'No valid editable model found' => 'To\'g\'ri model topilmadi',
    'Ok to proceed?' => 'Davom qildirishga rozimisiz?',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => 'PDF eksporti kartik-v/yii2-jadval kengaytmasi orqali hosil qilindi',
    'Page' => 'Sahifa',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'So\'rov tasdiqlandi! Yuklab olgan faylingiz saqlanganidan so\'ng bu oynani yopishingiz mumkin.',
    'Reset Grid' => 'Jadvalni yangilash',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Jadval ustunlarini excel ustunlari kabi chetidan tortib uzaytiring',
    'Show all data' => 'Hammasini ko\'rsatish',
    'Show first page data' => 'Birinchi sahifadagi qiymatlarni ko\'rsatish',
    'Tab Delimited Text' => 'Tab orqali ajratilgan matn',
    'Text' => 'Matn',
    'The CSV export file will be generated for download.' => 'Yuklab olishingiz uchun CSV fayl hosil qilinadi.',
    'The EXCEL export file will be generated for download.' => 'Yuklab olishingiz uchun EKSEL fayl hosil qilinadi.',
    'The HTML export file will be generated for download.' => 'Yuklab olishingiz uchun HTML fayl hosil qilinadi.',
    'The JSON export file will be generated for download.' => 'Yuklab olishingiz uchun JSON fayl hosil qilinadi.',
    'The PDF export file will be generated for download.' => 'Yuklab olishingiz uchun PDF fayl hosil qilinadi.',
    'The TEXT export file will be generated for download.' => 'Yuklab olishingiz uchun TEXT fayl hosil qilinadi.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Sahifa jamisi birinchi 3ta ustunlarni summasini va oxirgilarining o\'rtacha summasini ko\'rsatadi',
    'The table header sticks to the top in this demo as you scroll' => 'Bu namunada jadval tepasi sahifadan tushishingiz bilan tepada qoladi',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Jami {totalCount} yozuvlar bor. Hammasini ko\'rsatishga ishonchingiz komilmi?',
    'Update' => 'Yangilash',
    'View' => 'Ko\'rish',
    'Yii2 Grid Export (PDF)' => 'Yii2 Jadval Eksporti (PDF)',
    'export' => 'eksport',
    'grid-export' => 'jadval eksporti',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, jadval, eksport, yii2-jadval, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Kengaytmalari',
];
