<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Amallar',
    'Active' => 'Aktiv',
    'Add Book' => 'Kitob qo\'shish',
    'All' => 'Hammasi',
    'Are you sure to delete this item?' => 'O\'chirishga ishonchingiz komilmi?',
    'Book Listing' => 'Kitoblar ro\'yxati',
    'CSV' => '',
    'Clear selection' => 'Tanlovni bekor qilish',
    'Collapse' => 'Yig\'ish',
    'Collapse All' => 'Hammasini yig\'ish',
    'Comma Separated Values' => 'Vergul orqali ajratilgan qiymatlar',
    'Delete' => 'O\'chirish',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Fayllarni to\'g\'ri yuklash uchun brauzeringizdagi dialog oyna bloklovchilarini o\'chiring',
    'Download Selected' => 'Tanlanganlarni yuklab olish',
    'Excel' => '',
    'Expand' => 'Yoyish',
    'Expand All' => 'Hammasini yoyish',
    'Export' => 'Eksport',
    'Export All Data' => 'Hammasini eksport qilish',
    'Export Page Data' => 'Sahifadagilarni eksport qilish',
    'ExportWorksheet' => '',
    'Failed to update editable data due to an unknown server error' => 'Noma\'lum server xatoligi tufayli yangilanmadi',
    'Generated' => 'Hosil qilindi',
    'Generating the export file. Please wait...' => 'Fayl eksport uchun tayyorlanayapri. Iltimos kuting...',
    'Grid Export' => 'Jadvalni eksport qilish',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Noaktiv',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => 'Noto'g'ri yoki xato qiymat',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => '',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Hech narsa topilmadi',
    'No valid editable model found' => '',
    'Ok to proceed?' => 'Davom qilamizmi?',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Page' => 'Sahifa',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => 'Jadvalni yangilash',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'Show all data' => 'Hammasini ko\'rsatish',
    'Show first page data' => 'Birinchi sahifadagilarni ko\'rsatish',
    'Tab Delimited Text' => 'Tab orqali ajratilgan matn',
    'Text' => 'Matn',
    'The CSV export file will be generated for download.' => 'Yuklab olish uchun CSV fayl tayyorlanadi.',
    'The EXCEL export file will be generated for download.' => 'Yuklab olish uchun EXCEL fayl tayyorlanadi.',
    'The HTML export file will be generated for download.' => 'Yuklab olish uchun HTML fayl tayyorlanadi.',
    'The JSON export file will be generated for download.' => 'Yuklab olish uchun JSON fayl tayyorlanadi.',
    'The PDF export file will be generated for download.' => 'Yuklab olish uchun PDF fayl tayyorlanadi.',
    'The TEXT export file will be generated for download.' => 'Yuklab olish uchun MATN fayl tayyorlanadi.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => 'Skrol qilinsa jadval tepasi joyida qoladi',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Umumiy {totalCount} ta yozuv bor. Hammasini ko\'rsatishga rozimisiz?',
    'Update' => 'Yangilash',
    'View' => 'Ko\'rish',
    'Yii2 Grid Export (PDF)' => '',
    'export' => 'eksport',
    'grid-export' => '',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, jadval, eksport, yii2-jadval, pdf',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Kengaytmalari',
];
